### ISSUE TITLE
Error: Cannot resolve module 'logo.svg'

### ISSUE THREAD

**Issue by moroshko** [rpominov/svgo-loader#1]
http://stackoverflow.com/q/34480228/247243

**Comment by rpominov** [comment]
Does it work if you don't use svgo-loader? I suspect something wrong with the path to the file when you require() it.

**Comment by moroshko** [comment]
I tried to remove svgo-loader, and I get a similar error. 

Any idea what could be wrong with the path?

**Comment by rpominov** [comment]
Sorry, no idea. Try webpack's chat maybe https://gitter.im/webpack/webpack .

Closing as it doesn't seem as an issue with this loader.
