### ISSUE TITLE
Support for loaderUtils.getOptions

### ISSUE THREAD

**Issue by OriR** [rpominov/svgo-loader#10]
As of `loader-utils@0.2.17` there's a deprecation warning of `parseQuery`.
```
DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```
Instead of using `"loader-utils": "^0.2.16"` it's possible to also include the next major version that includes `getOptions` and use it if it exists with a fallback to `parseQuery`.

This will remove the warning generated by `loader-utils` and will start to phase out webpack 1.x in favor of webpack 2.x as it has become stable enough.

**Comment by rpominov** [comment]
Thanks for heads up! Wanna make a PR? 😅

**Comment by OriR** [comment]
Sure!
