### ISSUE TITLE
Cannot read property 'useConfig' of null

### ISSUE THREAD

**Issue by ACDR** [rpominov/svgo-loader#13]
After npm installed version `1.2.0` (`^1.1.0`) we encountered this error: `Module build failed: TypeError: Cannot read property 'useConfig' of null at Object.module.exports (.../node_modules/svgo-loader/index.js:13:13) @ ./source/index.js 79:0-29`

We fixed this by setting a custom config as shown in the README. If a custom config is now required for the loader to function I think it would be best to add a more specific error message such as "svgo-loader configuration not found.".

This error appears to have been caused by the change in how you're defining the `config` variable in this commit: https://github.com/rpominov/svgo-loader/commit/466238b7bce7e3982923c427e71a6f73261391e1

**Comment by joshuabalfe** [comment]
I have submitted a PR to fix this with a brief explanation here: https://github.com/rpominov/svgo-loader/pull/12
