### ISSUE TITLE
How to set output ?

### ISSUE THREAD

**Issue by Ricozor** [rpominov/svgo-loader#16]
Hi,
I'm realy newbie in webpack and i don't understand how exactly how work svgo-loader :
When  is it triggered ?
Is there au way to set  the output path whitout chanaguing the entry ?
I want to do something like this `$ svgo -f ../path/to/folder/with/svg/files -o ../path/to/folder/with/svg/output`  in my webpack.config.fs

thx for your help.

**Comment by rpominov** [comment]
Hey, as every webpack loader this one processes files that you `require()` in your js files.

You can set it up in a way that when you `const url = require('file.svg')` webpack would process this file through svgo, then put output to the folder with all your assets, and give you url to that output file in your `url` variable. See example setup here https://github.com/rpominov/svgo-loader/tree/master/example/success .

More in webpack docs https://webpack.github.io/docs/using-loaders.html .
