### ISSUE TITLE
How to prefix ids with svg filenames to make them unique?

### ISSUE THREAD

**Issue by kakadiadarpan** [rpominov/svgo-loader#18]
I want to generate unique ID names, which are prefixed with the SVG filename. I can do it in gulp [gulp-svgmin](https://github.com/ben-eb/gulp-svgmin#per-file-options), where it is being done from svgo actually.

```
gulp.task('default', function () {
    return gulp.src('src/*.svg')
        .pipe(svgmin(function getOptions (file) {
            var prefix = path.basename(file.relative, path.extname(file.relative));
            return {
                plugins: [{
                    cleanupIDs: {
                        prefix: prefix + '-',
                        minify: true
                    }
                }]
            }
        }))
        .pipe(svgstore())
        .pipe(gulp.dest('./dest'));
});
```

Do we have a similar option in svgo-loader?

**Comment by rpominov** [comment]
See #5 and in particular this comment https://github.com/rpominov/svgo-loader/pull/5#issuecomment-285718454

Closing this issue as a duplicate.
