### ISSUE TITLE
Fill option

### ISSUE THREAD

**Issue by klimashkin** [rpominov/svgo-loader#19]
I'm trying to enable only one plugin to remove fill/stroke
To do that svgo has [`fill: true`](https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md#1-config) option, so I'm trying to do 
```javascript
{
  loader: 'svgo-loader',
  options: {
    full: true,
    plugins: [
      {removeUselessStrokeAndFill: true},
    ],
  },
},
```
But then fill and stroke attributes remain. If I remove `full: true` those attributes are gone, but then other optimizations are applied as well

**Comment by rpominov** [comment]
This plugin simply passes options to svgo and doesn't process them in any way. Do these options work if you use them with svgo directly, without svgo-loader?
