### ISSUE TITLE
svgo dependency resolves as v0.7.2 with svgo-loader v2.0.0

### ISSUE THREAD

**Issue by Akaryatrh** [rpominov/svgo-loader#20]
Hey all,

While `svgo-loader` v2.0.0 should use at least `svgo` v1.0.0, it resolved to v0.7.2. Then, library returns an error while promise are only available from v1.0.0.

Could It comes from the fact that `svgo` is declared as a peer dependency?
Issue reproduced with both `yarn` and `npm`. FYI, loader works properly when `svgo` is installed manually.

**Edit:** While a peer dependency should be manually installed (as suggested by npm), documentation should be modified to:
```
$ npm install svgo svgo-loader --save-dev
$ yarn add svgo svgo-loader -D
```

**Comment by rpominov** [comment]
That's strange. We require the peer dependency to be `^1.0.0`: https://github.com/rpominov/svgo-loader/blob/3864ea3104bf53b8037016013e3cb0951439da1c/package.json#L28

The idea behind using peer dependency as opposed to a normal one is to let users install any version of `svgo` that they want.

Probably similar issue here #21

**Comment by Akaryatrh** [comment]
There was a time when `svgo` didn't publish a new version to `npm`, but now the version 1.0.3 is available there, so `0.7.2` resolution is kinda weird.

**Comment by rpominov** [comment]
I've just tried it out in an empty directory:

```
$ npm i svgo-loader
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN svgo-loader@2.0.0 requires a peer of svgo@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN test1@1.0.0 No description
npm WARN test1@1.0.0 No repository field.

+ svgo-loader@2.0.0
added 5 packages in 3.101s
```

```
$ npm list
test1@1.0.0 /private/tmp/test1
├── UNMET PEER DEPENDENCY svgo@^1.0.0
└─┬ svgo-loader@2.0.0
  └─┬ loader-utils@1.1.0
    ├── big.js@3.2.0
    ├── emojis-list@2.1.0
    └── json5@0.5.1

npm ERR! peer dep missing: svgo@^1.0.0, required by svgo-loader@2.0.0
```

```
$ npm install svgo
npm WARN test1@1.0.0 No description
npm WARN test1@1.0.0 No repository field.

+ svgo@1.0.3
added 42 packages in 6.701s
```

Seems like everything works as expected now.

**Comment by koutsenko** [comment]
Why you closed that issue? Now svgo-loader downloads old version svgo as dependency. In order to make it work i must manually install fresh svgo in additional and nowhere can read about that.

Best regards.

**Comment by rpominov** [comment]
Hi @koutsenko , I wasn't able to reproduce this as shown in https://github.com/rpominov/svgo-loader/issues/20#issuecomment-343890264

How do you reproduce it?

**Comment by koutsenko** [comment]
Just working with my npm & webpack3-bundled js project.
1. with svgo-loader 1.2.1, all works like charm, without any svgo entries
2. updated the package.json entry: 1.2.1 -> 2.0.0
3. totally removed npm_modules and package-lock.json
4. npm install. All modules are installed from scratch.
5. npm build/watch and a problem appears.
6. manually add svgo 1.0.3 entry, again npm install and all works.

Maybe its some ^ or ~ versioning-related magic in svgo-loader deps? 

п.с. мой английский ужасен :)

**Comment by koutsenko** [comment]
My [package.json](https://github.com/koutsenko/m3w-sol/blob/master/package.json) file

**Comment by Akaryatrh** [comment]
@koutsenko [Readme file](https://github.com/rpominov/svgo-loader/commit/da367968a2e678443f2e5f358ffe03bbc6d308e4#diff-04c6e90faac2675aa89e2176d2eec7d8) has been updated and now asks to install both `svgo` along `svg-loader`. This is following npm recommendations about peer dependencies.

**Comment by rpominov** [comment]
I've investigated a bit more. Here is how it happens: 

- `css-loader` has a dependency on `svgo`;
- if you've installed `css-loader` and `svgo-loader` it worked, but by accident (`svgo-loader` used `svgo` installed with `css-loader`);
- when you update `svgo-loader` it no longer works.

But, after step 4 you should see a warning like this:

> npm WARN svgo-loader@2.0.0 requires a peer of svgo@^1.0.0 but none is installed. You must install peer dependencies yourself.

And yes, our readme asks to install `svgo`. Although maybe we should state it more explicitly if already three people stumbled upon this independently.

**Comment by rpominov** [comment]
I've added a warning to the readme https://github.com/rpominov/svgo-loader/commit/2f4563bf4fa07ccdfaf82850bf10cead5552879e

**Comment by Akaryatrh** [comment]
>I've added a warning to the readme 2f4563b

@rpominov I was thinking about the reason you chose to declare svg-loader as a peer dependency. You wanted the user to be free to install any version of `svgo` but finally you need at least the version `1.0.0`. So maybe you should declare now `svgo` as a regular dependency?

**Comment by rpominov** [comment]
Hm. Not sure how it will work then. For example:

- Someone installs `svg-loader` and gets `svgo@1.0.0` as a normal dependency
- `svgo` releases `1.1.0`

How do they switch to `svgo@1.1.0` in this case?

**Comment by rpominov** [comment]
`babel-loader` also specifies `babel` as a peer dependency, btw: https://github.com/babel/babel-loader/blob/8b07d5d7b7e584a28d8c07bde23f342e675c7b9a/package.json#L18

But I honestly don't know what is the best practice for cases like this. Would appreciate if someone could investigate.

**Comment by Akaryatrh** [comment]
>How do they switch to svgo@1.1.0 in this case?

While you declare `svgo` with a caret range as `^1.0.0`, user will get latest version lower than `2.0.0`.
=> https://github.com/npm/node-semver#caret-ranges-123-025-004b

Finally, declare a dependency as a peer ensures that if any version already installed (as It happened here with `css-loader`) doesn't match your package definition, the user will get a warning about an unmet version.

You can also keep `svgo` as a peer dependency, but then in `Readme` file modify instructions to:
`npm install svgo@^1.0.0 svgo-loader --save-dev` to ensure that an incompatible version of `svgo` doesn't get installed.

**Comment by jgchenu** [comment]
I encountered the same error as you did. Then I used npm install svgo and npm i svgo -g and added "peerDependencies" to package.json: {
     "svgo": "^1.0.0"
   },then npm i ,at last I solve my problem @Akaryatrh
