### ISSUE TITLE
Load config from svgoConfig.yml file?

### ISSUE THREAD

**Issue by Friksel** [rpominov/svgo-loader#25]
Hi, I just installed your svgo-loader and it looks great, but I can't figure out by the readme if it's possible to load the svgo-config via its yaml file. If there is a way: How can we do that with this loader? If there's not: could you please add an option to load the svgo config from the yaml file?

The reason I'm using yaml files for svgo config is that the config is pretty large and reused over multiple projects. Including all its settings would make the webpack config overly complex to read too. So it would be great if there is a way to load the config, like normal svgo can.
Thanks!

**Comment by rpominov** [comment]
Hi, this isn't possible currently. I don't have time and energy to do this, would be great if someone made a PR.

**Comment by rpominov** [comment]
@Friksel I was able to do it :-) Available in `v2.2.0` please check. I've added the instructions to README.

**Comment by Friksel** [comment]
@rpominov Wow, that's great! Just checked it and it works flawlessly! Thanks a lot for this, this speeds up my workflow so much since I'm working a lot with svg's and use a lot of compression settings in the yaml files per project. Thanks again!

**Comment by rpominov** [comment]
You're welcome 👍

**Comment by Friksel** [comment]
@rpominov  Haha, I just noticed I gave the thumbsup and chearing thing to my own post instead of yours. crazy :)
