### ISSUE TITLE
Does svgo-loader cache result?

### ISSUE THREAD

**Issue by a-x-** [rpominov/svgo-loader#26]
... or does run svgo every build?

**Comment by rpominov** [comment]
I think webpack should cache the result if this API still works: https://github.com/rpominov/svgo-loader/blob/ef3b9250c423f9618eb8a23c95f74bc415e03510/index.js#L8 (it was quite a few major webpack releases since this code was written)

**Comment by a-x-** [comment]
Yay, thanks!
