### ISSUE TITLE
feature request: Append config to imported external config

### ISSUE THREAD

**Issue by wigglepixel** [rpominov/svgo-loader#29]
For several projects I use one svgoconfig-file per project for several different types of svgs.
Inside the svgoconfig file I use 'preserve' inside cleanupIDs to preserve some element-IDs to be able to adress them by javascript to animate them. But what ID I'd like to preserve in one svg I'd like to get rid of in another svg file.

To avoid using the same preserved IDs for all svg-files going through svgo with this loader I could create several svgoconfig files. One for each svg-type. But I have lots of settings set and that's a lot of duplicated code that I need to maintain everytime also.

It would be a lot better if the svgo-loader could instead load the external svgo-file with all settings in and append the config of the module itself (as set in the config-object) to those imported settings. That way we could set the cleanupIDs - preserve array in the webpack config file and still keep the major list of general svgo settings in the svgoconfig file.

So the only change the loader should need to be able to do this is loading the external config first and APPEND, rather than overwrite, the 'local' loader-config object to the imported config result.

Would that be possible to build in this very handy loader? Thanks in advance and for the great work.

**Comment by TrySound** [comment]
Hi, you can use the new `preset-default` plugin with the latest svgo version
https://github.com/svg/svgo/releases/tag/v2.4.0
