### ISSUE TITLE
Issues: when using loader multiple times problems occur (+solution)

### ISSUE THREAD

**Issue by Friksel** [rpominov/svgo-loader#31]
Problem: as title says.

At line 53 of index.js the loader is not cloning the options/config object before passing it to the svgo module:

```javascript
var svgo = new Svgo(config);
```

This is throwing issues when using the loader more than once in webpack as the config object is changed after first use. This is also stated in the official documentation of loader-utils' `getOptions()`: **If you pass it on to another library, make sure to make a deep copy of it**

> Please note: The returned options object is read-only. It may be re-used across multiple invocations.
> If you pass it on to another library, make sure to make a deep copy of it

source: https://algobank.oecd.org:4430/SDG_tracker/SDG_website/tree/eeaf0f7a10d802f3444fa0f9e59af80ac5b3e48d/node_modules/loader-utils/#getoptions

So to fix this issue it's just a matter of adding three dots and two accolades to clone before passing to svgo() (tested here and works fine):

**solution**

```javascript
var svgo = new Svgo({ ...config });
```

**Comment by rpominov** [comment]
Could you submit a pull request with a fix? I will merge it and release a new version to NPM

**Comment by Friksel** [comment]
> Could you submit a pull request with a fix? I will merge it and release a new version to NPM

Seriously? As I wrote in my post the solution is just to add the 5 mentioned characters.
