### ISSUE TITLE
SVGO v2

### ISSUE THREAD

**Issue by KrakenTyio** [rpominov/svgo-loader#33]
Pls update repo based on new version of svgo https://github.com/svg/svgo/releases/tag/v2.0.0

**Comment by TrySound** [comment]
Coming soon

**Comment by Diono** [comment]
any news on this? please :)

**Comment by TrySound** [comment]
I will work on migration tomorrow

**Comment by sergeykonovalenko** [comment]
> I will work on migration tomorrow

Thanks a lot!

**Comment by TrySound** [comment]
See here

**Comment by 19h47** [comment]
@TrySound Thanks a lot 🙏🏼

**Comment by rpominov** [comment]
Done and published in v3.0.0
