### ISSUE TITLE
Error in parsing SVG: Non-whitespace before first tag

### ISSUE THREAD

**Issue by jawn-ha** [rpominov/svgo-loader#37]
ic_vendor_360.svg:1 Uncaught Error: Module build failed (from ../node_modules/svgo-loader/index.js):
Error: Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: i
    at Object.loader (Users/zhj/Documents/fe-dev/test/node_modules/svgo-loader/index.js:14)
    at eval (ic_vendor_360.svg:1)
    at Object../modules/holographic-archive/src/icons/svg/brand/ic_vendor_360.svg (index.js:2507)
    at __webpack_require__ (index.js:833)
    at fn (index.js:130)
    at webpackContext (eval at ./modules/test/src/icons/svg sync recursive \.svg$ (index.js:2496), <anonymous>:31:9)
    at Array.map (<anonymous>)
    at requireAll (index.js?fb20:3)
    at eval (index.js?fb20:4)
    at Module../modules/test/src/icons/index.js (index.js:2485)
    at __webpack_require__ (index.js:833)

webpack config
![image](https://user-images.githubusercontent.com/16000122/111768237-a52b5900-88e2-11eb-97b2-c6ea38bf76bc.png)

**Comment by TrySound** [comment]
Hi @jawn-ha . Could you provide svg file which produces this error?

**Comment by jawn-ha** [comment]
> Hi @jawn-ha . Could you provide svg file which produces this error?

this is the svg icons
[svg_icon.zip](https://github.com/svg/svgo-loader/files/6179734/svg_icon.zip)

**Comment by TrySound** [comment]
Cannot reproduce. Could you create repository with reproduction including webpack setup?

**Comment by jawn-ha** [comment]
> Cannot reproduce. Could you create repository with reproduction including webpack setup?

I create an repo to reproduce the question https://github.com/jawn-ha/svgo-test. 
You can clone and run` npm install` and` npm run serve `to reproduce

**Comment by TrySound** [comment]
I see. It's not svgo-loader issue. Put svg-sprite-loader before svgo-loader. It's stupid webpack loaders ordering.

**Comment by jawn-ha** [comment]
> I see. It's not svgo-loader issue. Put svg-sprite-loader before svgo-loader. It's stupid webpack loaders ordering.
I had tried this，if you put  svg-sprite-loader before svgo-loader, svgo-loader will not working

**Comment by jawn-ha** [comment]
I had tried this，if you put svg-sprite-loader before svgo-loader, svgo-loader will not working
> I see. It's not svgo-loader issue. Put svg-sprite-loader before svgo-loader. It's stupid webpack loaders ordering.

**Comment by TrySound** [comment]
I don't see any issue with svgo. It produces correct svg, it removes fill from path. Maybe something wrong with svg-sprite-loader. I'm not experienced with it.

**Comment by jawn-ha** [comment]
I have solved it, you are right! The cause of the problem is my SVGO config is wrong. Thanks for your patience

> I don't see any issue with svgo. It produces correct svg, it removes fill from path. Maybe something wrong with svg-sprite-loader. I'm not experienced with it.
