### ISSUE TITLE
svgo loader multiple versions breaks extendDefaultPlugins

### ISSUE THREAD

**Issue by ntucker** [rpominov/svgo-loader#38]
Instructions include
```js
const { extendDefaultPlugins } = require('svgo');
```

However, this only works if the svgo version used by svgo-loader is the same as wherever is using svgo-loader and thus, importing extendDefaultPlugins. If not, the default plugins might include new ones that don't exist in the version used in this plugin.

Solution1: switch back to peerDeps

Solution2: re-export svgo things you expect users to use like extendDefaultPlugins so they can use a version consistent with this library.

**Comment by TrySound** [comment]
Added declarative preset support in https://github.com/svg/svgo/releases/tag/v2.4.0
Installed svgo is no longer required.
