### ISSUE TITLE
Publish new release to npm with svgo 2.5.0

### ISSUE THREAD

**Issue by decademoon** [rpominov/svgo-loader#43]
Is there any plan to publish a new release of this package to npm? I would really like to get this commit https://github.com/svg/svgo-loader/commit/5bd5786678233abd8d00c75e3fd59d285bd29eab.

Also why is `svgo` a dependency and not a peer dependency? It seems I have to wait for `svgo-loader` to update its `svgo` dependency if I want to use a newer version of `svgo`.

**Comment by TrySound** [comment]
You still can upgrade transitive svgo by reinstalling svgo-loader

**Comment by decademoon** [comment]
You're right, svgo-loader depends on svgo version `^2.2.0` which includes version 2.5. I guess the version I had installed was pinned to some earlier version.
