### ISSUE TITLE
Webpack ignores svgo-loader

### ISSUE THREAD

**Issue by PurpleTape** [rpominov/svgo-loader#44]
Hello!

I've run into this issue that webpack is ignoring svgo-loader. That is, no optimization rules are applied to the svg file. Just load raw file. What do you think this might be related to?

My config:
```js
module: {
  rules: [
    // ...

    {
      test: /\.(svg)(\?.*)?$/,
      type: 'asset/resource',
      generator: {
        filename: 'img/[name].[hash:8][ext]'
      },
      use: [
        {
          loader: 'svgo-loader',
          options: {
            configFile: false,
            plugins: [
              'preset-default'
            ]
          }
        }
      ]
    },

    // ...
  ]
}
```

I'm using vue-cli under webpack 5 (around ~5.54.0 version)
svgo-loader: "^3.0.0"

Thanks!

**Comment by nikbrunner** [comment]
We are having the same problem. Single plugins like `removeAttr` for example, get respected, but `preset-default` does nothing. I would like, that `svgo-loader` using the same defaults as the `svgo` command line tool.

### My dependencies
```json
"svgo": "2.4.",
"svgo-loader": "3.0.0",
"webpack": "5.51.1",
"webpack-cli": "4.8.0",
"webpack-dev-server": "4.0.",
```

**Comment by rpominov** [comment]
Hello. We're low on manpower, but if you figure out the problem and submit a PR with a fix, I can review and merge it, and release a new version for you.

**Comment by PurpleTape** [comment]
Hello! 
I was wrong, everything works great! The point is that it didn't remove license comments that start with "<!--!". But that is by design, according to the [source code](https://github.com/svg/svgo/blob/main/plugins/removeComments.js). Although I was confused at first, I eventually figured it out. Thank you for such a cool optimizer and for your time!
