### ISSUE TITLE
What versions of webpack does `svgo-loader` support?

### ISSUE THREAD

**Issue by s100** [rpominov/svgo-loader#52]
This is a question. `svgo-loader` specifies a [development dependency on `webpack@^5.74.0`](https://github.com/svg/svgo-loader/blob/c15d6911479f1ab7eebfbe5141f2155ff531e8c2/package.json#L25), so we assume it supports `webpack@5`. But we are attempting to use it with `webpack@4` and we are seeing some problems. Is this supported? In general, what versions of `webpack` are supported?

The best way to answer this question would be to add a `peerDependencies` field to your `package.json`.

Thank you for your free work!

**Comment by rpominov** [comment]
We might have accidentally lost webpack@4 support recently: https://github.com/svg/svgo-loader/commit/c15d6911479f1ab7eebfbe5141f2155ff531e8c2#commitcomment-87911075

What problems do you have? Can you give me reproduction instructions?

**Comment by s100** [comment]
The error we see (lightly redacted) is:

```
12:45:42  ERROR in ./node_modules/<our package name>/.../chevron.svg
12:45:42  Module build failed (from ./node_modules/svgo-loader/index.js):
12:45:42  TypeError: this.getOptions is not a function
12:45:42      at Object.loader (/home/.../node_modules/svgo-loader/index.js:5:43)
12:45:42      at Object.module.exports (/home/.../node_modules/svgo-loader/index.js:21:10)
```

From poking around, it looks there are other loaders which have similar issues, but I haven't looked any deeper yet. I will ask my colleague to try to produce a minimal reproduction but I can't promise anything unfortunately.

**Comment by rpominov** [comment]
Thanks!

> I will ask my colleague to try to produce a minimal reproduction but I can't promise anything unfortunately.

No need, I see what the problem is. Will look in to it.

**Comment by rpominov** [comment]
Should be fixed in 3.0.3, please check.

**Comment by s100** [comment]
That worked, thank you for your impressively prompt action on this! I would still recommend adding a peer dependency, something like `"webpack": "^4.17.2 || ^5.74.0"`, to make those supported versions of webpack explicit.

**Comment by BryanAdamss** [comment]
same issue
