### ISSUE TITLE
SVGO v3.0.0 support

### ISSUE THREAD

**Issue by sarahp06** [rpominov/svgo-loader#53]
Hello! 👋 Just a question, are there plans to support `svgo` v3.0.0 (https://github.com/svg/svgo/releases/tag/v3.0.0) which was released recently?

Many thanks! 😃

**Comment by rpominov** [comment]
Hello! Not sure I will have time soon to research what needs to be done to add the support.

@TrySound Maybe you're interested in doing the update?

Also, not sure whether it's better to try to keep support of both v2 and v3, or release a major version of `svgo-loader` that looses support of v2.
