### ISSUE TITLE
Support unquoted attributes

### ISSUE THREAD

**Issue by vzaidman** [rpominov/svgo-loader#9]
if you have svgs with unquoted attributes such as:
`xmlns="http://www.w3.org/2000/svg" width=20px height=20px`

The error: `Error in parsing SVG: Unquoted attribute value` is emitted.

I've created a loader to temporary fix this in webpack:
https://www.npmjs.com/package/xml-fix-loader

```
{
  test: /\.svg$/,
  use: [
    { loader: 'file-loader' },
    { loader: 'svgo-loader' },
    { loader: 'xml-fix-loader' }
  ]
}
```
Also opened a bug on `svgo`:
https://github.com/svg/svgo/issues/678

**Comment by rpominov** [comment]
Sounds like an issue with SVGO itself, and should be fixed there. Thank you for creating issue in SVGO repository. This one should be closed I think.
